apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-smpchnl-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-smpchnl-carrier
  chart:
    git: https://github.com/alurujawahar/spdra-platform.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net.org3ambassador.getthespiderman.com:8443
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devcarrier-net-auth
      adminsecretprefix: secret/data/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/data/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: smpchnl      
    orderer:
      address: orderer1.org1ambassador.getthespiderman.com:8443
    anchorstx: |-
      CtUCChUKEwgCGgYIsOm5lAYiB3NtcGNobmwSuwIKuAIKB3NtcGNobmwSYxJhCgtBcHBsaWNhdGlv
      bhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACIP
      CgtFbmRvcnNlbWVudBIAIgsKB1JlYWRlcnMSABrHARLEAQoLQXBwbGljYXRpb24StAEIARKvAQoK
      Y2Fycmllck1TUBKgAQgBGlQKC0FuY2hvclBlZXJzEkUSOwo5CjRwZWVyMC5jYXJyaWVyLW5ldC5v
      cmczYW1iYXNzYWRvci5nZXR0aGVzcGlkZXJtYW4uY29tEPtBGgZBZG1pbnMaBwoDTVNQEgAiCwoH
      V3JpdGVycxIAIgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAKgZBZG1p
      bnM=

