apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-smpchnl-manufacturer
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-smpchnl-manufacturer
  chart:
    git: https://github.com/alurujawahar/spdra-platform.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.manufacturer-net.org2ambassador.a.getthespiderman.com:8443
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devmanufacturer-net-auth
      adminsecretprefix: secret/data/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/data/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: smpchnl      
    orderer:
      address: orderer1.org1ambassador.a.getthespiderman.com:8443
    anchorstx: |-
      CuYCChUKEwgCGgYIpumzlAYiB3NtcGNobmwSzAIKyQIKB3NtcGNobmwSaBJmCgtBcHBsaWNhdGlv
      bhJXCAESUwoPbWFudWZhY3R1cmVyTVNQEkAaBwoDTVNQEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3Jz
      ZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAGtMBEtABCgtBcHBsaWNhdGlvbhLAAQgB
      ErsBCg9tYW51ZmFjdHVyZXJNU1ASpwEIARpbCgtBbmNob3JQZWVycxJMEkIKQAo7cGVlcjAubWFu
      dWZhY3R1cmVyLW5ldC5vcmcyYW1iYXNzYWRvci5hLmdldHRoZXNwaWRlcm1hbi5jb20Q+0EaBkFk
      bWlucxoHCgNNU1ASACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACIL
      CgdSZWFkZXJzEgAqBkFkbWlucw==

